### ISSUE TITLE
Little important

### ISSUE THREAD

**Issue by Naster17** [Nick-Vinesmoke/Heat-RAT#16]
![Снимок экрана (287)](https://github.com/Nick-Vinesmoke/Heat-RAT/assets/62520991/bf0a8ccf-d98d-4dd9-b2e6-e7608a36b0c1)
Bro, you have been pwned

Не подумай нечего, просто предупредил чтобы это не нашел ещё кто-то кроме меня
Но теперь я могу сказать тебе, Слава Украине! :)

**Comment by Nick-Vinesmoke** [comment]
Дяк, але шоти не мої тому я не парюсь

**Comment by Nick-Vinesmoke** [comment]
![image](https://github.com/Nick-Vinesmoke/Heat-RAT/assets/123866627/51191996-9bee-4478-8861-6892a3ed974b)
диви яке співпадіння, я думав, що людина якої скріншоти з рашки

**Comment by Naster17** [comment]
Николаев если xyos смотреть

**Comment by Naster17** [comment]
И да, класный ратник 💯
