### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by erofcon** [Nick-Vinesmoke/Heat-RAT#6]
Unfortunately Windows Defender detects a virus

**Comment by erofcon** [comment]
Are there solutions?

**Comment by Nick-Vinesmoke** [comment]
Oh yes I'll fix it in next update that will come soon

**Comment by Nick-Vinesmoke** [comment]
or you can crypt it

**Comment by Nick-Vinesmoke** [comment]
⭐Please, star this repo if it was helpful⭐

**Comment by Nick-Vinesmoke** [comment]
> Oh yes I'll fix it in next update that will come soon

I know how to fix it, but I get some bugs so I think update will be today or tomorrow
