### ISSUE TITLE
About penetrations

### ISSUE THREAD

**Issue by mans5647** [Nick-Vinesmoke/Heat-RAT#7]
Okey, program is here but i don't understanding how to connect to other PCs? Is there some instruction?

**Comment by Nick-Vinesmoke** [comment]
[Do like this and all will work](https://sites.google.com/view/heat-rat)

**Comment by Nick-Vinesmoke** [comment]
My rat setup like other rats to many sessions

**Comment by mans5647** [comment]
thanks, and on final which file containing functionality to manage victim'c pc?

**Comment by Nick-Vinesmoke** [comment]
### 📠Functions:

> !screenshot"
> - do a screenshot and sent to you

> "!photoWebcam"
>- do a photo from the webcam and sent to you

> "!openLink"
>- open the link on the victim's computer

> "!directory"
>- get a path to rat virus

> "!directoryContent"
>- get all files name placed in the same directory with virus

> "!createFolder"
>- create a folder on the victim's computer

> "!deleteFolder"
>- delete a folder on the victim's computer

> "!deleteFile"
>- delete a file on the victim's computer

> downloadFile"
>- download the file to the victim's computer

> "!video"
>- rec the video from the victim's webcam, duration in seconds

> "!audio"
>- rec the audio from the victim's microphone, duration in seconds

> "!runFile"
>- run the file on the victim's computer

> "!volume"
>- change the volume on the victim's computer

> "!turnOff"
>- shutdown the victim's computer

> "!restart"
>- restart the victim's computer

> "!alt+f4"
>- alt+f4 =)

> "!crazyCursor"
>- change mouse buttons

> "!wallpaper"
>- change the wallpaper on the victim's compute

> "!move"
>- move the virus to the directory

> "!rename"
>- rename the virus

> "!encrypt"
>- encrypt file on the victim's computer

> "!decrypt"
>- decrypt file on the victim's computer

> "!logs"
>- grab and send logs from the victim's computer

> "!screamer"
>- screamer :O

> "!moveFile"
>- move the file to the directory on victim's computer

> "!lock"
>- #winlock ('._.')

> "!downloadFolder"
>- download folder to the victim's computer

> "!processes"
>- show process list

> "!closeProces"
>- close process

> "!banTM"
>- ban task manager

> "!message"
>- show text message

> "!CMDbomb"
>- booom

---
